### ISSUE TITLE
What is this project?

### ISSUE THREAD

**Issue by tombh** [Shougo/neoinclude.vim#40]
I found this through coc.nvim, it links to lots of interesting projects, so I like to check them out even if I don't recognise the name. However I landed here and couldn't tell what it was for.

**Comment by Shougo** [comment]
Please read the documentation.

It extends Vim's standard feature `:help 'path'` and include completion.

**Comment by tombh** [comment]
I still don't understand. I've been using Vim for 5 years. Why is this so hard for me to understand? Your description in your reply isn't in the docs. _How_ does it extend `help path`? What is a specific example of a problem that this plugin solves? Can you make a gif?

**Comment by Shougo** [comment]
> Why is this so hard for me to understand? 

Because this plugin is for library for other plugins.
You don't use it directly.

```vim
*neoinclude.txt*	Include completion framework for neocomplete/deoplete/ncm.
```

> What is a specific example of a problem that this plugin solves?

So the example is for neocomplete/deoplete/ncm.

> It extends Vim's standard feature :help 'path' and include completion.

`'path'` is built-in feature.  But it is hard to use for other plugins.
So I have created the plugin.

neoinclude can parse your source code and returns included files list.

**Comment by tombh** [comment]
I'm still not entirely sure what it does. But thank you for taking the time to explain.

**Comment by iasj** [comment]
@tombh I'm also a Neovim plugin developer and I think what @Shougo meant is that they use it to help them in the development of other plugins. That's why it's called a framework.

Being a framework means that you will be framed to work in that particular manner.

But to be fair, I also didn't understand at first, and I'm even not sure now, so it begs the following question:

@Shougo , is this plugin made for the regular user or I was right to say that it's meant as a helper for development?

I need to say it lacks further information about this. I'm building a small init.vim for a few beginner user (friends), and I need to know if they will ever need this plugin for any regular USE of deoplete.

**Comment by Shougo** [comment]
> @Shougo , is this plugin made for the regular user or I was right to say that it's meant as a helper for development?

It is created for plugin developer including me.
Similar plugin: context_filetype.vim
https://github.com/Shougo/context_filetype.vim

> I need to say it lacks further information about this. I'm building a small init.vim for a few beginner user (friends), and I need to know if they will ever need this plugin for any regular USE of deoplete.

neoinclude plugin extends deoplete feature.  But it is not needed for all users.

Note: context_filetype plugin is recommended for deoplete user though.
